# Generated by Django 3.1.5 on 2021-01-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_raiting',
            new_name='author_rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_raiting',
            new_name='comment_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_raiting',
            new_name='post_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='article_text',
            new_name='text',
        ),
    ]
